archive_url: add Wget exit code to error message…
…regarding a failed attempt to archive a URL.

diff --git a/archive_url b/archive_url
--- a/archive_url
+++ b/archive_url
@@ -20,7 +20,7 @@ set -u
 set -e
 
 PROG=archive_url
-VERSION='2025-01-05-03'
+VERSION='2025-01-05-04'
 FORCE=0
 DRYRUN=0
 QUIET=0
@@ -173,7 +173,7 @@ check_and_archive_url()
     if test "$DRYRUN" -eq 0; then
       verb_nl ' triggering archiving ...'
       wget "$WGETVERB" -O/dev/null -- "${ARCHIVE}${URL}" ||
-        err 'error archiving URL'
+        err "error archiving URL (Wget exit code $?)"
     else
       verb_nl ' not archived (dry run)'
     fi
