archive_url: consistently use upper case ERROR

diff --git a/archive_url b/archive_url
--- a/archive_url
+++ b/archive_url
@@ -20,7 +20,7 @@ set -u
 set -e
 
 PROG=archive_url
-VERSION='2024-12-05-02'
+VERSION='2024-12-16-01'
 FORCE=0
 DRYRUN=0
 QUIET=0
@@ -144,17 +144,17 @@ while getopts ':hVLfnqvw:r' OPT; do
     'v') VERBOSE=1;;
     'w') WAITTIME="$OPTARG";;
     'r') JITTERWAIT=1;;
-    '?') echo "$PROG: error: unknown option '-$OPTARG'"; print_usage; exit 1;;
-    ':') echo "$PROG: error: argument required for option '-$OPTARG'";
+    '?') echo "$PROG: ERROR: unknown option '-$OPTARG'"; print_usage; exit 1;;
+    ':') echo "$PROG: ERROR: argument required for option '-$OPTARG'";
          print_usage; exit 1;;
-    *)   echo "$PROG: error: getopts() failure"; exit 1;;
+    *)   echo "$PROG: ERROR: getopts() failure"; exit 1;;
   esac
 done
 shift $((OPTIND - 1))
 
 if ! printf -- '%s\n' "$WAITTIME" | grep -Eq '^([0-9]+(\.[0-9]*)?|\.[0-9]+)$'
 then
-  echo "$PROG: error: TIME must be a decimal number"
+  echo "$PROG: ERROR: TIME must be a decimal number"
   exit 1
 fi
 
