fix getops() error reporting in shell scripts
* Use "silent" error reporting
* Print the unknown option letter with a prepended '-'
* Handle case of missing argument for a known option

diff --git a/archive_url b/archive_url
--- a/archive_url
+++ b/archive_url
@@ -20,7 +20,7 @@ set -u
 set -e
 
 PROG=archive_url
-VERSION='2024-06-21-01'
+VERSION='2024-09-22-01'
 FORCE=0
 DRYRUN=0
 QUIET=0
@@ -133,7 +133,7 @@ do_wait() {
   verb_nl ' done'
 }
 
-while getopts hVLfnqvw:r OPT; do
+while getopts ':hVLfnqvw:r' OPT; do
   case "$OPT" in
     'h') print_help; exit 0;;
     'V') print_version; print_copyright; exit 0;;
@@ -144,7 +144,9 @@ while getopts hVLfnqvw:r OPT; do
     'v') VERBOSE=1;;
     'w') WAITTIME="$OPTARG";;
     'r') JITTERWAIT=1;;
-    '?') echo "$PROG: error: unknown option '$1'"; print_usage; exit 1;;
+    '?') echo "$PROG: error: unknown option '-$OPTARG'"; print_usage; exit 1;;
+    ':') echo "$PROG: error: argument required for option '-$OPTARG'";
+         print_usage; exit 1;;
     *)   echo "$PROG: error: getopts() failure"; exit 1;;
   esac
 done
diff --git a/ipcalc b/ipcalc
--- a/ipcalc
+++ b/ipcalc
@@ -1,7 +1,7 @@
 #! /usr/bin/env bash
 
 # ipcalc - print information about an IPv4 network
-# Copyright (C) 2013-2019 by Erik Auerswald <auerswal@unix-ag.uni-kl.de>
+# Copyright (C) 2013-2024 by Erik Auerswald <auerswal@unix-ag.uni-kl.de>
 #
 # Copying and distribution of this file, with or without modification,
 # are permitted in any medium without royalty provided the copyright
@@ -11,7 +11,7 @@
 set -u
 
 PROG="$(basename $0)"
-version='2019-09-25-01'
+version='2024-09-22-01'
 
 print_version()
 {
@@ -20,7 +20,7 @@ print_version()
 
 print_copyright()
 {
-  echo 'Copyright (C) 2013-2019 by Erik Auerswald <auerswal@unix-ag.uni-kl.de>'
+  echo 'Copyright (C) 2013-2024 by Erik Auerswald <auerswal@unix-ag.uni-kl.de>'
 }
 
 print_license()
@@ -256,7 +256,7 @@ print_table()
   done
 }
 
-while getopts 'hVLtbcn' OPT; do
+while getopts ':hVLtbcn' OPT; do
   case "$OPT" in
     'h') print_help; exit 0;;
     'V') print_version; print_copyright; exit 0;;
@@ -265,7 +265,9 @@ while getopts 'hVLtbcn' OPT; do
     'b') ;;
     'c') ;;
     'n') ;;
-    '?') echo "$PROG: ERROR: unknown option '$1'";
+    '?') echo "$PROG: ERROR: unknown option '-$OPTARG'";
+         print_usage; exit 1;;
+    ':') echo "$PROG: ERROR: argument required for option '-$OPTARG'";
          print_usage; exit 1;;
     *) echo "$PROG: ERROR: getopts() failure"; exit 1;;
   esac
diff --git a/isascii b/isascii
--- a/isascii
+++ b/isascii
@@ -1,7 +1,7 @@
 #! /bin/sh
 
 # isascii - check if all input bytes comprise only 7-bit ASCII
-# Copyright (C) 2022 Erik Auerswald <auerswal@unix-ag.uni-kl.de>
+# Copyright (C) 2022-2024 Erik Auerswald <auerswal@unix-ag.uni-kl.de>
 #
 # This program is free software: you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
@@ -24,7 +24,7 @@
 set -u
 
 PROG="$(basename "$0")"
-VERSION='2022-07-19-01'
+VERSION='2024-09-22-01'
 
 print_version()
 {
@@ -33,7 +33,7 @@ print_version()
 
 print_copyright()
 {
-  echo 'Copyright (C) 2022 Erik Auerswald <auerswal@unix-ag.uni-kl.de>'
+  echo 'Copyright (C) 2022-2024 Erik Auerswald <auerswal@unix-ag.uni-kl.de>'
 }
 
 print_license()
@@ -87,13 +87,15 @@ EOH
 }
 
 VERBOSE=0
-while getopts 'hVLv' OPT; do
+while getopts ':hVLv' OPT; do
   case "$OPT" in
     'h') print_help; exit 0;;
     'V') print_version; exit 0;;
     'L') print_version; print_license; exit 0;;
     'v') VERBOSE=1;;
-    '?') echo "$PROG: ERROR: unknown option '$1'";
+    '?') echo "$PROG: ERROR: unknown option '-$OPTARG'";
+         print_usage; exit 1;;
+    ':') echo "$PROG: ERROR: argument required for option '-$OPTARG'";
          print_usage; exit 1;;
     *) echo "$PROG: ERROR: getopts() failure"; exit 1;;
   esac
diff --git a/ping_scan b/ping_scan
--- a/ping_scan
+++ b/ping_scan
@@ -2,7 +2,7 @@
 
 # Send an ICMP echo request to each of the IPs given.
 #
-# Copyright (C) 2011-2022 Erik Auerswald <auerswal@unix-ag.uni-kl.de>
+# Copyright (C) 2011-2024 Erik Auerswald <auerswal@unix-ag.uni-kl.de>
 #
 # Copying and distribution of this file, with or without modification,
 # are permitted in any medium without royalty provided the copyright
@@ -11,14 +11,14 @@
 #
 # Requires the ping program of Solaris or an output-compatible one.
 
-VERSION=2022-11-25-01
+VERSION='2024-09-22-01'
 PROG="$(basename "$0")"
 PING="${PING_WRAPPER:-ping}"
 
 version()
 {
   echo "$PROG version $VERSION"
-  echo "Copyright (c) 2011-2022 by Erik Auerswald <auerswal@unix-ag.uni-kl.de>"
+  echo "Copyright (c) 2011-2024 by Erik Auerswald <auerswal@unix-ag.uni-kl.de>"
 }
 
 usage() { echo "Usage: $PROG [-h] [-L] [-V] [-t TIMEOUT] [-v] [-u] [IP...]"; }
@@ -62,15 +62,18 @@ license()
 TIMEOUT=1
 VERB=0
 UNREACHABLE=0
-while getopts t:hvuLV OPT; do
+while getopts ':t:hvuLV' OPT; do
   case "$OPT" in
-    t) TIMEOUT=${OPTARG:-2};;
-    h) help; exit 0;;
-    v) VERB=1;;
-    u) UNREACHABLE=1;;
-    L) version; license; exit 0;;
-    V) version; exit 0;;
-    ?) usage; exit 1;;
+    't') TIMEOUT=${OPTARG:-2};;
+    'h') help; exit 0;;
+    'v') VERB=1;;
+    'u') UNREACHABLE=1;;
+    'L') version; license; exit 0;;
+    'V') version; exit 0;;
+    '?') echo "$PROG: error: unknown option '-$OPTARG'"; usage; exit 1;;
+    ':') echo "$PROG: error: argument required for option '-$OPTARG'";
+         usage; exit 1;;
+    *)   echo "$PROG: error: getopts() failure"; exit 1;;
   esac
 done
 shift $((OPTIND - 1))
diff --git a/rfc-reader b/rfc-reader
--- a/rfc-reader
+++ b/rfc-reader
@@ -80,7 +80,7 @@ copyright()
 
 version()
 {
-  local V="0.69"
+  local V="0.70"
   printf -- "%s\n" "$B version $V"
 }
 
@@ -140,13 +140,17 @@ usage()
 }
 
 # parse options
-while getopts 'hVLt' OPT; do
+while getopts ':hVLt' OPT; do
  case "$OPT" in
    'h') version; copyright; license; echo; usage; exit 0;;
    'V') version; copyright; exit 0;;
    'L') version; copyright; license; exit 0;;
    't') unset DISPLAY;;
-   '?') exit 1;;
+   '?') printf -- '%s: ERROR: unknown option "-%s"\n' "$B" "$OPTARG";
+        usage; exit 1;;
+   ':') printf -- '%s: ERROR: argument required for option "-%s"\n' \
+                  "$B" "$OPTARG";
+        usage; exit 1;;
    *) printf -- '%s: ERROR: getopts() failure\n' "$B"; exit 1;;
  esac
 done
