archive_url: sprinkle option terminators

diff --git a/archive_url b/archive_url
--- a/archive_url
+++ b/archive_url
@@ -20,7 +20,7 @@ set -u
 set -e
 
 PROG=archive_url
-VERSION='2021-03-17-01'
+VERSION='2021-03-17-02'
 FORCE=0
 DRYRUN=0
 VERBOSE=0
@@ -111,18 +111,18 @@ check_and_archive_url()
   URL="$1"
   test "$VERBOSE" -eq 1 && printf -- '%s' "$URL"
   test "$FORCE" -eq 1 && STATUS='false' ||
-    STATUS="$(wget -q -O- "${CHECK}${URL}" | jq '.archived_snapshots != {}')"
+    STATUS="$(wget -q -O- -- "${CHECK}${URL}" | jq '.archived_snapshots != {}')"
   if test "$STATUS" = 'true'; then
     test "$VERBOSE" -eq 1 && echo ' is archived'
   else
     if test "$DRYRUN" -eq 0; then
       test "$VERBOSE" -eq 1 && echo ' is attempted to be archived'
-      wget -nv -O/dev/null "${ARCHIVE}${URL}" || echo 'error archiving URL'
+      wget -nv -O/dev/null -- "${ARCHIVE}${URL}" || echo 'error archiving URL'
     else
       test "$VERBOSE" -eq 1 && echo ' is not archived'
     fi
   fi
-  sleep "$WAITTIME"
+  sleep -- "$WAITTIME"
 }
 
 if test "$#" -eq 0; then
