ipcalc: removed trailing whitespace, updated copyright

diff --git a/ipcalc b/ipcalc
--- a/ipcalc
+++ b/ipcalc
@@ -1,7 +1,7 @@
 #! /usr/bin/env bash
 
 # ipcalc - print information about an IPv4 network
-# Copyright (C) 2013 by Erik Auerswald <auerswal@unix-ag.uni-kl.de>
+# Copyright (C) 2013, 2016 by Erik Auerswald <auerswal@unix-ag.uni-kl.de>
 #
 # Copying and distribution of this file, with or without modification,
 # are permitted in any medium without royalty provided the copyright
@@ -11,7 +11,7 @@
 set -u
 
 PROG="$(basename $0)"
-version='2013-05-05-01'
+version='2016-05-15-01'
 
 print_version()
 {
@@ -20,7 +20,7 @@ print_version()
 
 print_copyright()
 {
-  echo 'Copyright (C) 2013 by Erik Auerswald <auerswal@unix-ag.uni-kl.de>'
+  echo 'Copyright (C) 2013, 2016 by Erik Auerswald <auerswal@unix-ag.uni-kl.de>'
 }
 
 print_license()
@@ -261,7 +261,7 @@ while getopts hVLt OPT; do
     't') print_table; exit 0;;
     '?') echo "$PROG: ERROR: unknown option '$1'";
          print_usage; exit 1;;
-    *) echo "$PROG: ERROR: getopts() failure"; exit 1;; 
+    *) echo "$PROG: ERROR: getopts() failure"; exit 1;;
   esac
 done
 shift $(($OPTIND - 1))
@@ -277,7 +277,7 @@ test "$IP" = "$1" ||
 shift
 
 test $# -eq 2 &&
-  { test "$1" = "/" || 
+  { test "$1" = "/" ||
     { echo "$PROG: ERROR: seperator must be a '/'"; print_usage; exit 1; } &&
   shift; }
 
@@ -322,7 +322,7 @@ IPBIN=0
 for i in ${IP//./ }; do
   test "$i" -ge 0 -a "$i" -le 255 -a "$ctr" -lt 4 ||
     { echo "$PROG: ERROR: $IP is no IPv4 address"; print_usage; exit 1; }
-  IPBIN=$(( ($IPBIN<<8) + $i)) 
+  IPBIN=$(( ($IPBIN<<8) + $i))
   let ctr++
 done
 ctr=0
@@ -330,7 +330,7 @@ MASKBIN=0
 for i in ${MASK//./ }; do
   test "$i" -ge 0 -a "$i" -le 255 -a "$ctr" -lt 4 ||
     { echo "$PROG: ERROR: $IP is no IPv4 address"; print_usage; exit 1; }
-  MASKBIN=$(( ($MASKBIN<<8) + $i)) 
+  MASKBIN=$(( ($MASKBIN<<8) + $i))
   let ctr++
 done
 NETBIN=$(($IPBIN & $MASKBIN))
