reachability_monitor: prevent normal use
The reachability_monitor script does not always clean
up after itself, i.e., it may leave host monitors
running after the main script has exited.  But just
adding a call to stop_monitors() sometimes results
in the error that one of the PIDs to kill does not
exist (this PID may even be used by a different process).
Thus this is not yet ready for general use.

If you know what you are doing and I can trust you,
you can still use the script, but you have to ensure
that everything is cleaned up afterwards.

diff --git a/reachability_monitor b/reachability_monitor
--- a/reachability_monitor
+++ b/reachability_monitor
@@ -1,7 +1,7 @@
 #! /bin/bash
 
 # reachability_monitor - report reachability changes for a set of hosts
-# Copyright (C) 2022 Erik Auerswald
+# Copyright (C) 2022-2023 Erik Auerswald
 #
 # This program is free software: you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
@@ -19,7 +19,16 @@
 set -e
 
 PROG="$(basename "$0")"
-VERSION='2022-12-06-01'
+VERSION='2023-02-10-01'
+
+# XXX this script is currently broken, i.e., started host monitors are not
+# XXX reliably removed when the script exits, so refuse to work unless the
+# XXX user knows what they are doing and can be trusted to do the right thing,
+# XXX i.e., clean up afterwards
+test -n "$TRUST_ME_I_KNOW_WHAT_IM_DOING" || {
+  printf -- '\n***\n*** --- this script does not work yet ---\n***\n\n'
+  exit 42
+}
 
 # different ping implementations require different options to send one probe
 # and wait at most 1s for an answer
@@ -36,7 +45,7 @@ RELOADING=0
 PRINTING=0
 
 print_copyright() {
-  echo 'Copyright (C) 2022 Erik Auerswald'
+  echo 'Copyright (C) 2022-2023 Erik Auerswald'
 }
 
 print_version() {
