rfc-reader: tweak getopts() error handling
Distinguish between an unknown option and any other getopts()
failure.

The getopts() error message for an unknown option is sufficient,
but I have never seen any other getopts() failure, so emit a
diagnostic just in case this ever happens.

diff --git a/rfc-reader b/rfc-reader
--- a/rfc-reader
+++ b/rfc-reader
@@ -54,7 +54,7 @@ copyright()
 
 version()
 {
-  local V="0.50"
+  local V="0.51"
   printf -- "%s\n" "$B version $V"
 }
 
@@ -109,13 +109,14 @@ usage()
 }
 
 # parse options
-while getopts hVLt OPT; do
+while getopts 'hVLt' OPT; do
  case "$OPT" in
    'h') version; copyright; license; echo; usage; exit 0;;
    'V') version; copyright; exit 0;;
    'L') version; copyright; license; exit 0;;
    't') unset DISPLAY;;
-   *) exit 1;;
+   '?') exit 1;;
+   *) printf -- '%s: Error: getopts() failure\n' "$B"; exit 1;;
  esac
 done
 shift $((OPTIND - 1))
