rfc-reader: fallback to current terminal w/o XTerm
If the X Window System is available, but no usable terminal
emulator program is found, try to display the RFC(-like) file
in the current terminal.

This is hardly tested, since my GNU/Linux system provides a
usable X Window System environment.

This change splits one code block to separate looking for a
usable terminal emulator from deciding to use a new terminal
emulator instance, and then moves a lot of code around.

diff --git a/rfc-reader b/rfc-reader
--- a/rfc-reader
+++ b/rfc-reader
@@ -73,7 +73,7 @@ copyright()
 
 version()
 {
-  local V="0.60"
+  local V="0.61"
   printf -- "%s\n" "$B version $V"
 }
 
@@ -318,61 +318,8 @@ PSL='1'
 PA='0'
 test "$P" = 'most' && PSL='2' PA='1'
 
-# use current terminal if X-Windows is not available
+# find a usable terminal emulator program or disable X Window System use
 DISPLAY=${DISPLAY:=}
-PAGINATED=1
-awk '/\014/{exit 1}' "$F" && {
-  printf -- '%s: WARN: no Form Feed characters in RFC/I-D "%s"\n' "$B" "$R"
-  PAGINATED=0
-  case "$P" in
-    less|more|most) PO="$PO -s";;
-  esac
-}
-test -z "$DISPLAY" && test "$PAGINATED" -eq '1' && {
-  # check terminal size
-  TL="${TL:=${LINES:=}}"
-  test -z "$TL" && TL="$(stty size 2>/dev/null | cut -d' ' -f1)"
-  test -z "$TL" && TL="$(tput lines 2>/dev/null)"
-  test -z "$TL" && TL="$(resize -u 2>/dev/null \
-                         | sed -n '/LINES/s/^.*=\([0-9]\+\).*$/\1/p')"
-  test -z "$TL" &&
-    { printf -- '%s: ERROR: cannot determine terminal height\n' "$B"; exit 1; }
-  test "$TL" -lt "$((L+PSL))" && {
-    printf -- '%s: ERROR: terminal too short (%d lines, but %d needed)\n' \
-               "$B" "$TL" "$((L+PSL))"
-    exit 1
-  }
-  TC="${TC:=${COLUMNS:=}}"
-  test -z "$TC" && TC="$(stty size 2>/dev/null | cut -d' ' -f2)"
-  test -z "$TC" && TC="$(tput cols 2>/dev/null)"
-  test -z "$TC" && TC="$(resize -u 2>/dev/null \
-                         | sed -n '/COLUMNS/s/^.*=\([0-9]\+\).*$/\1/p')"
-  test -z "$TC" &&
-    { printf -- '%s: ERROR: cannot determine terminal width\n' "$B"; exit 1; }
-  test "$TC" -lt "$C" && {
-    printf -- '%s: ERROR: terminal too narrow (%d columns, but %d needed)\n' \
-              "$B" "$TC" "$C"
-    exit 1
-  }
-  # format RFC(-like) text for current terminal's height
-  L="$((TL-PSL))"
-}
-
-# reformat RFC(-like) text for chosen terminal which has L lines for viewing
-# text content (including SL status line(s) used by the pager)
-# shellcheck disable=SC2026
-if test "$PAGINATED" -eq 1; then
-  awk -vn_lines="$L" -vpg_adds="$PA" \
-    '!/\f/{line++; print};
-     /\f/{for (i=line; i<n_lines; i++) print ""; line=0}
-     END {if (line || pg_adds){for (i=line; i<n_lines-pg_adds; i++) print ""}}'\
-    "$F" | sed '1s/^'$'\uFEFF''//;/^$/!s/^/  /' > "$FMT"
-else
-  sed '1s/^'$'\uFEFF''//;/^$/!s/^/  /' "$F" \
-  | awk '!text && /^[[:space:]]*$/{next}; !text{text=1}; {print}' > "$FMT"
-fi
-
-# open suitable terminal window if X-Windows is available
 test -n "$DISPLAY" && {
   # determine window sizes
   Y=$(xrandr | sed -n '/\*/s/^[^x]*x *\([0-9]*\)[^0-9].*$/\1/p' | head -n1)
@@ -437,9 +384,69 @@ test -n "$DISPLAY" && {
         ;;
     esac
   done
-  test -x "$(command -v "$XT")" ||
-    { printf -- '%s: ERROR: no usable terminal program found\n' "$B"; exit 1; }
+  test -x "$(command -v "$XT")" || {
+    printf -- \
+      '%s: WARN: no usable terminal program found, using current terminal\n' \
+      "$B"
+    DISPLAY=''
+  }
+}
 
+# use current terminal if X Window System is not usable
+PAGINATED=1
+awk '/\014/{exit 1}' "$F" && {
+  printf -- '%s: WARN: no Form Feed characters in RFC/I-D "%s"\n' "$B" "$R"
+  PAGINATED=0
+  case "$P" in
+    less|more|most) PO="$PO -s";;
+  esac
+}
+test -z "$DISPLAY" && test "$PAGINATED" -eq '1' && {
+  # check terminal size
+  TL="${TL:=${LINES:=}}"
+  test -z "$TL" && TL="$(stty size 2>/dev/null | cut -d' ' -f1)"
+  test -z "$TL" && TL="$(tput lines 2>/dev/null)"
+  test -z "$TL" && TL="$(resize -u 2>/dev/null \
+                         | sed -n '/LINES/s/^.*=\([0-9]\+\).*$/\1/p')"
+  test -z "$TL" &&
+    { printf -- '%s: ERROR: cannot determine terminal height\n' "$B"; exit 1; }
+  test "$TL" -lt "$((L+PSL))" && {
+    printf -- '%s: ERROR: terminal too short (%d lines, but %d needed)\n' \
+               "$B" "$TL" "$((L+PSL))"
+    exit 1
+  }
+  TC="${TC:=${COLUMNS:=}}"
+  test -z "$TC" && TC="$(stty size 2>/dev/null | cut -d' ' -f2)"
+  test -z "$TC" && TC="$(tput cols 2>/dev/null)"
+  test -z "$TC" && TC="$(resize -u 2>/dev/null \
+                         | sed -n '/COLUMNS/s/^.*=\([0-9]\+\).*$/\1/p')"
+  test -z "$TC" &&
+    { printf -- '%s: ERROR: cannot determine terminal width\n' "$B"; exit 1; }
+  test "$TC" -lt "$C" && {
+    printf -- '%s: ERROR: terminal too narrow (%d columns, but %d needed)\n' \
+              "$B" "$TC" "$C"
+    exit 1
+  }
+  # format RFC(-like) text for current terminal's height
+  L="$((TL-PSL))"
+}
+
+# reformat RFC(-like) text for chosen terminal which has L lines for viewing
+# text content (including SL status line(s) used by the pager)
+# shellcheck disable=SC2026
+if test "$PAGINATED" -eq 1; then
+  awk -vn_lines="$L" -vpg_adds="$PA" \
+    '!/\f/{line++; print};
+     /\f/{for (i=line; i<n_lines; i++) print ""; line=0}
+     END {if (line || pg_adds){for (i=line; i<n_lines-pg_adds; i++) print ""}}'\
+    "$F" | sed '1s/^'$'\uFEFF''//;/^$/!s/^/  /' > "$FMT"
+else
+  sed '1s/^'$'\uFEFF''//;/^$/!s/^/  /' "$F" \
+  | awk '!text && /^[[:space:]]*$/{next}; !text{text=1}; {print}' > "$FMT"
+fi
+
+# open suitable terminal window if X-Windows is available
+test -n "$DISPLAY" && {
   # open terminal window with a pager displaying the RFC(-like) text
   # shellcheck disable=SC2086
   "$XT" $XO "$XF" $G $T"$B - $(basename "$R")" $E "$FMT"
