rfc-reader: adjust check for terminal height
If rfc-reader is called without DISPLAY environment variable, it
tries to use the current terminal. This can only work if the
current terminal is of sufficient size. This size check must
consider the differences in status line count of pagers.

diff --git a/rfc-reader b/rfc-reader
--- a/rfc-reader
+++ b/rfc-reader
@@ -38,7 +38,7 @@ test \( -d "$RFCCACHE" \) -a \( -r "$RFCCACHE" \) &&
 
 version()
 {
-  local V="0.30"
+  local V="0.31"
   printf -- "%s\n" "$B version $V"
   echo 'Copyright (C) 2011-2019 Erik Auerswald <auerswal@unix-ag.uni-kl.de>'
 }
@@ -166,7 +166,7 @@ test -z "$DISPLAY" && {
   TL="${TL:=${LINES:=}}"
   test -z "$TL" && TL="$(stty size 2>/dev/null | cut -d' ' -f1)"
   test -z "$TL" && { echo 'ERROR: cannot determine terminal height'; exit 1; }
-  test "$TL" -lt "$L" && { echo 'ERROR: terminal too short'; exit 1; }
+  test "$TL" -lt "$((L+PSL))" && { echo 'ERROR: terminal too short'; exit 1; }
   TC="${TC:=${COLUMNS:=}}"
   test -z "$TC" && TC="$(stty size 2>/dev/null | cut -d' ' -f2)"
   test -z "$TL" && { echo 'ERROR: cannot determine terminal width'; exit 1; }
